# These miscellaneous locale-specific messages are used by the kiwi.db package
# and probably won't be of interest to an application.
# Author: Mark Lindner
# Locale: default (US English)
#
kiwi.db.message.not_null=The value for {0} cannot be NULL.
kiwi.db.message.greater_than_zero=The value for {0} must be greater than zero.
kiwi.db.message.not_negative=The value for {0} must be greater than or equal to zero.
#
# end of message file