# These are general-purpose locale-specific messages, for use in things like
# buttons, common dialog boxes, tooltips, and so on. Most of these are used by
# the Kiwi Toolkit itself, but many can be used by an application.
# Locale: default (US English)
# Author: Mark Lindner
#
kiwi.button.ok=OK
kiwi.button.cancel=Cancel
kiwi.button.yes=Yes
kiwi.button.no=No
kiwi.button.new=New
kiwi.button.copy=Copy
kiwi.button.edit=Edit
kiwi.button.delete=Delete
kiwi.button.save=Save
kiwi.button.next=Next
kiwi.button.back=Back
kiwi.button.finish=Finish
kiwi.button.home=Home
kiwi.button.undo=Undo
kiwi.button.close=Close
kiwi.button.dismiss=Dismiss
kiwi.button.clear=Clear
kiwi.button.browse=Browse
kiwi.button.start=Start
kiwi.button.stop=Stop
kiwi.button.help=Help
kiwi.button.search=Search
kiwi.button.detail=Detail
kiwi.button.column_sel=Column Selector
kiwi.dialog.prompt.date_select=Select a date:
kiwi.dialog.title.date_select=Select a Date
kiwi.dialog.prompt=Prompt.
kiwi.dialog.prompt.input=Input:
kiwi.dialog.prompt.message=Message.
kiwi.dialog.prompt.question=Question?
kiwi.dialog.title.input=Input
kiwi.dialog.title.message=Message
kiwi.dialog.title.question=Question
kiwi.dialog.prompt.directory_select=Select a directory:
kiwi.dialog.title.directory_select=Select Directory
kiwi.dialog.title.login=Login
kiwi.dialog.prompt.login=Please log in:
kiwi.dialog.prompt.username=Username:
kiwi.dialog.prompt.password=Password:
kiwi.dialog.title.progress=Progress
kiwi.dialog.prompt.wait=Please wait...
kiwi.dialog.title.console=Console
kiwi.dialog.title.select=Select an Item
kiwi.dialog.title.select_file=Select File
kiwi.tooltip.move_down=Move Down
kiwi.tooltip.move_up=Move Up
kiwi.tooltip.delete=Delete
kiwi.tooltip.new=New
kiwi.tooltip.cut=Cut
kiwi.tooltip.copy=Copy
kiwi.tooltip.paste=Paste
kiwi.tooltip.clear=Clear
kiwi.tooltip.italic=Italic
kiwi.tooltip.bold=Bold
kiwi.tooltip.underline=Underline
kiwi.tooltip.plain=Plain
kiwi.tooltip.help=Help
kiwi.tooltip.search=Search
kiwi.tooltip.zoom_in=Zoom In
kiwi.tooltip.zoom_out=Zoom Out
kiwi.tooltip.actual_size=Actual Size
kiwi.tooltip.select_date=Select Date
kiwi.tooltip.select_file=Select File
kiwi.tooltip.add_item=Add Item
kiwi.tooltip.remove_sel_items=Remove Selected Items
kiwi.dialog.message.login_failed=Login failed. Please try again.
kiwi.dialog.message.select_item=Please make a selection.
kiwi.label.name=Name
kiwi.label.value=Value
kiwi.label.directory_list=Directory List
#
# end of message file
