# These miscellaneous locale-specific messages are used by various Kiwi
# classes and probably won't be of interest to an application.
# Author: Mark Lindner
# Locale: default (US English)
#
kiwi.warning.doc_not_found=Document Not Found
kiwi.warning.doc_not_found.desc=The document at {0} could not be loaded.
kiwi.path_editor.tooltip.move_down=Move Down
kiwi.path_editor.tooltip.move_up=Move Up
kiwi.path_editor.tooltip.delete=Delete
kiwi.path_editor.tooltip.new=New
kiwi.path_editor.column=Directory List
kiwi.dialog.title.property_editor=Property Editor
kiwi.dialog.property_editor.edit_property=Enter a name for the property:
kiwi.dialog.property_editor.property_exists=That property already exists.
kiwi.dialog.property_editor.delete_property=Delete this property?
kiwi.dialog.property_editor.save_failed=Couldn't save properties:\n\n{0}
kiwi.dialog.prompt.property_editor=Property file: {0}
kiwi.db.warning.null=The value for {0} cannot be NULL.
kiwi.db.warning.positive=The value for {0} must be greater than zero.
kiwi.warning.html.doc_not_found=<html><body><h3>Document Not Found</h3><p>The document at <b>{0}</b> could not be loaded.</body></html>
kiwi.column.file=File
kiwi.column.size=Size
kiwi.column.date=Date
kiwi.column.time=Time
kiwi.label.all_filesystems=All Filesystems
#
# end of message file