package jworkspace.ui.desktop;

public interface IDesktopActions {

    String CREATE_SHORTCUT = "CREATE_SHORTCUT";

    String PASTE = "Paste";
    String SELECT_ALL = "Select All";
    String ARRANGE = "Arrange Icons";

    String CLOSE_ALL_WINDOWS = "CLOSE_ALL_WINDOWS";

    String BACKGROUND = "BACKGROUND";
    String CHOOSE_BACKGROUND_IMAGE = "CHOOSE_BACKGROUND_IMAGE";
    String TOGGLE_WALLPAPER = "TOGGLE_WALLPAPER";
    String TOGGLE_WALLPAPER_IN_DIALOG = "TOGGLE_WALLPAPER_IN_DIALOG";
    String TOGGLE_GRADIENT = "TOGGLE_GRADIENT";
    String GRADIENT_FILL = "GRADIENT_FILL";
    String CHOOSE_GRADIENT_COLOR_1 = "CHOOSE_GRADIENT_COLOR_1";
    String CHOOSE_GRADIENT_COLOR_2 = "CHOOSE_GRADIENT_COLOR_2";

    String NEW_SHORTCUT = "New Shortcut";

}
