/* ----------------------------------------------------------------------------
   The Kiwi Toolkit - A Java Class Library
   Copyright (C) 1998-2008 Mark A. Lindner

   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public License as
   published by the Free Software Foundation; either version 2 of the
   License, or (at your option) any later version.

   This library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this library; if not, see <http://www.gnu.org/licenses/>.
   ----------------------------------------------------------------------------
*/

package com.hyperrealm.kiwi.event.workspace;

import java.util.EventObject;

// ---

import com.hyperrealm.kiwi.ui.WorkspaceEditor;

/**
 * Event generated by a <code>WorkspaceManager</code> object to notify
 * listeners that a <code>WorkspaceEditor</code>'s state has changed in some
 * way.
 *
 * @author Mark Lindner
 * @see com.hyperrealm.kiwi.ui.WorkspaceEditor
 * @see com.hyperrealm.kiwi.ui.WorkspaceManager
 * @see WorkspaceListener
 */

public class WorkspaceEvent extends EventObject {

    private final WorkspaceEditor editor;

    /**
     * Construct a new <code>WorkspaceEvent</code>.
     *
     * @param source The source of the event.
     * @param editor The <code>WorkspaceEditor</code> associated with this
     *               event.
     */

    public WorkspaceEvent(Object source, WorkspaceEditor editor) {
        super(source);
        this.editor = editor;
    }

    /**
     * Get the editor associated with this event.
     */

    public WorkspaceEditor getEditor() {
        return (editor);
    }

}
